### PR TITLE
Another version of FizzBuzz for comparison

### PR DESCRIPTION
**Pull request by keleshev**

### CODE REVIEW

**Comment by erikrose** [comment]
That's funny: aside from the `for` loop, this is exactly what I wrote my first time through. :-) I thought it was a little hard to match up the zeros in the match clauses with what they corresponded to (as a reader), so I tried ifs instead. I think `cond` might actually be the most readable way (since it removes the nesting) though I haven't tried it yet.

**Comment by erikrose** [comment]
Wait, sorry, `cond` was Clojure. That's what I get for learning 2 languages at once. :-)

**Comment by keleshev** [comment]
Perhaps something like:

```ocaml
let is_divisible_by n div = n mod div = 0

let to_string n =
  match is_divisible_by n 3, is_divisible_by n 5 with
  | true,  true  -> "FizzBuzz"
  | true,  false -> "Fizz"
  | false, true  -> "Buzz"
  | false, false -> string_of_int n

let () =
  for i = 1 to 100 do
    print_endline (to_string i)
  done
```

**Comment by keleshev** [comment]
Or this:

```ocaml
let to_string n =
  let is_divisible_by div = n mod div = 0 in
  match is_divisible_by 3, is_divisible_by 5 with
  | true,  true  -> "FizzBuzz"
  | true,  false -> "Fizz"
  | false, true  -> "Buzz"
  | false, false -> string_of_int n

let () =
  for i = 1 to 100 do
    print_endline (to_string i)
  done
```

**Pull request closed without merging**
